# Generated by Django 4.0.3 on 2022-05-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_alter_answer_question_alter_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='number',
            field=models.IntegerField(auto_created=True, blank=True, null=True),
        ),
    ]
