# Generated by Django 4.0.3 on 2022-05-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_answer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='number',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
    ]
