# Generated by Django 4.0.3 on 2022-05-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0009_remove_marksofuser_question_marksofuser_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksofuser',
            name='question',
            field=models.ManyToManyField(blank=True, to='testApp.question'),
        ),
    ]
